# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character] 
success_symbol = ""
error_symbol = ""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# disable the took message


[line_break]
disabled = true

[directory]
truncation_length = 2
format = "$path"

[username]
format = "char"
disabled = true

[hostname]
ssh_only = false
#format = "@$hos tname"
format = "@local &rarr;"
disabled = true

[localip]
ssh_only = false
format = '@$localipv4'
disabled = true

[git_status]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[terraform]
disabled = true
