# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took $duration"

[character] # The name of the module we are configuring is "character"
success_symbol = "" # The "success_symbol" is set to "➜" with color "bold green"
error_symbol = "" # The "success_symbol" is set to "➜" with color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = true

[directory]
truncation_length = 2
format = "$path"

[username]
format = "char"
disabled = true
show_always = true

[hostname]
ssh_only = false
#format = "@$hostname"
format = "@local &rarr;"
disabled = true

[localip]
ssh_only = false
format = '@$localipv4'
disabled = true

[git_status]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[terraform]
disabled = true
